services:
  - type: web
    name: envismoney
    runtime: node
    region: frankfurt
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
